import { useCallback, useEffect, useRef, useState } from "react";
import { router, useFocusEffect } from "expo-router";
import { Animated, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "@/auth/auth-context";
import { supabase } from "@/auth/supabase";
import { colors } from "@/theme/colors";
import { tr } from "@/i18n";
import { BottomNav } from "@/navigation/bottom-nav";

type Row = { rank: number; display_name: string; player_code: string; trophies: number; tier?: string; is_me?: boolean; wins?: number; losses?: number };
type History = { match_id: string; mode: string; opponent_name: string; score_for: number; score_against: number; outcome: "WIN" | "LOSS"; finished_at: string };

export default function Competition() {
  const { profile } = useAuth(); const [table, setTable] = useState<Row[]>([]); const [history, setHistory] = useState<History[]>([]); const pulse = useRef(new Animated.Value(.86)).current;
  const load = useCallback(async () => { const [standings, matches] = await Promise.all([supabase.rpc("competition_nearby"), supabase.rpc("competition_my_history")]); if (!standings.error) setTable((standings.data ?? []) as Row[]); if (!matches.error) setHistory((matches.data ?? []) as History[]); }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { Animated.spring(pulse,{toValue:1,tension:130,friction:7,useNativeDriver:true}).start(); }, [pulse, profile?.trophies]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Pressable accessibilityRole="button" onPress={() => router.replace("/lobby")} hitSlop={12}><Text style={styles.back}>←</Text></Pressable><Text style={styles.kicker}>{tr.competition.kicker}</Text><Text style={styles.title}>{tr.competition.title}</Text>
    <Animated.View style={[styles.trophy,{transform:[{scale:pulse}]}]}><Text style={styles.trophyValue}>{profile?.trophies ?? 0}</Text><Text style={styles.trophyLabel}>{(table.find(row=>row.is_me)?.tier ?? "BRONZE")} · {tr.common.trophies.toUpperCase()}</Text><Text style={styles.trophyNote}>{tr.competition.quickOnly}</Text></Animated.View>
    <Section title={tr.competition.table}>{table.map(row => <View key={row.player_code} style={[styles.rankRow, (row.is_me || row.player_code === profile?.playerCode) && styles.me]}><Text style={styles.rank}>{row.rank}</Text><View style={styles.person}><Text style={styles.name}>{row.display_name}</Text><Text style={styles.record}>{row.tier ?? "BRONZE"}</Text></View><Text style={styles.points}>{row.trophies}</Text></View>)}</Section>
    <Section title={tr.competition.history}>{history.length ? history.map(item => <View key={item.match_id} style={styles.history}><View><Text style={[styles.outcome, item.outcome === "WIN" ? styles.win : styles.loss]}>{item.outcome === "WIN" ? tr.competition.winLabel : tr.competition.lossLabel}</Text><Text style={styles.opponent}>{item.opponent_name}</Text></View><View style={styles.scoreBlock}><Text style={styles.matchScore}>{item.score_for}–{item.score_against}</Text><Text style={styles.mode}>{item.mode === "QUICK" ? tr.quick.action : tr.lobby.friendRoom}</Text></View></View>) : <Text style={styles.empty}>{tr.competition.noHistory}</Text>}</Section>
  </ScrollView><BottomNav /></SafeAreaView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, page: { padding: 22, gap: 20, paddingBottom: 42 }, back: { color: colors.text, fontSize: 30 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1.7 }, title: { color: colors.text, fontSize: 35, lineHeight: 39, fontWeight: "900", letterSpacing: -1.1 }, trophy: { borderRadius: 16, padding: 20, backgroundColor: colors.accent }, trophyValue: { color: colors.background, fontWeight: "900", fontSize: 48, lineHeight: 50 }, trophyLabel: { color: colors.background, fontWeight: "900", fontSize: 10, letterSpacing: 1.5 }, trophyNote: { color: colors.background, opacity: .75, marginTop: 12, fontSize: 12 }, section: { gap: 7 }, sectionTitle: { color: colors.muted, fontWeight: "900", fontSize: 10, letterSpacing: 1.3 }, rankRow: { flexDirection: "row", alignItems: "center", gap: 12, padding: 12, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, me: { borderColor: colors.accent }, rank: { color: colors.accent, width: 20, fontWeight: "900", textAlign: "center" }, person: { flex: 1 }, name: { color: colors.text, fontWeight: "900" }, record: { color: colors.muted, fontSize: 11, marginTop: 2 }, points: { color: colors.text, fontWeight: "900", fontSize: 18 }, history: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderRadius: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: 13 }, outcome: { fontSize: 10, fontWeight: "900", letterSpacing: .7 }, win: { color: colors.primary }, loss: { color: colors.danger }, opponent: { color: colors.text, fontWeight: "800", marginTop: 4 }, scoreBlock: { alignItems: "flex-end" }, matchScore: { color: colors.text, fontSize: 20, fontWeight: "900" }, mode: { color: colors.muted, fontSize: 10, marginTop: 3 }, empty: { color: colors.muted, backgroundColor: colors.surface, borderRadius: 12, padding: 15 } });
