const dictionaries = {
  tr: {
    common: { signIn: "Giriş yap", signUp: "Hesap aç", player: "oyuncu", trophies: "kupa", chatStyle: "SOHBET BALONU" },
    nav: { play: "Oyna", friends: "Arkadaşlar", league: "Lig", style: "Stil", account: "Hesap menüsü" },
    social: { online: "Çevrim içi", inMatch: "Maçta", offline: "Çevrim dışı", recent: "SON OYNANANLAR", remove: "Arkadaşlıktan çıkar", block: "Engelle", manage: "Arkadaşı yönet", inviteSent: "Maç daveti gönderildi" },
    effects: { lastSecond: "SON SANİYE CEVABI", cooldown: "Mesaj göndermek için biraz bekle" },
    auth: { checking: "Oturum kontrol ediliyor", kicker: "FOOTBALL LINK · MAÇ GİRİŞİ", title: "İki kulüp.", titleAccent: "Tek bağlantı.", lead: "Futbol hafızanı gerçek rakiplere karşı sahaya çıkar.", welcome: (name: string) => `Hoş geldin, ${name}.`, activeMatch: "DEVAM EDEN MAÇ", botMatch: "Test botuna karşı", friendRoom: "Arkadaş odası", matchCenter: "Maç merkezine git", displayName: "Görünen ad", email: "E-posta", password: "Şifre · en az 6 karakter", or: "YA DA", confirmationSent: "Onay bağlantısını e-postana gönderdik. Onayladıktan sonra giriş yapabilirsin.", errors: { invalidLogin: "E-posta veya şifre eşleşmedi.", registered: "Bu e-posta zaten kayıtlı. Giriş yapmayı dene.", password: "Şifre en az 6 karakter olmalı.", fallback: "İşlem tamamlanamadı. Bağlantını kontrol edip tekrar dene.", invalidResponse: "Giriş yanıtı doğrulanamadı." } },
    lobby: { signOut: "Oturumu kapat", noSession: "Oturum yok", kicker: "MAÇ MERKEZİ", title: "Nasıl oynamak\nistiyorsun?", botA11y: "Bota karşı test maçı başlat", recommended: "TEST İÇİN ÖNERİLEN", botTitle: "Bota karşı oyna", botCopy: "Rakip beklemeden tüm maç akışını tek cihazda dene.", botAction: "Test maçını başlat", friendRoom: "ARKADAŞ ODASI", roomTitle: "Aynı odaya bağlan", roomCopy: "Bir oda oluşturup davet gönder veya arkadaşının kodunu gir.", roomCode: "Maç odası kodu", createRoom: "Yeni oda oluştur", shareInvite: "Daveti paylaş", inviteTitle: "Football Link maç daveti", inviteMessage: (url: string) => `Football Link'te benimle oyna: ${url}`, roomCreated: "Oda hazır. Daveti paylaşabilir veya maça katılabilirsin.", join: "Odaya katıl", friends: "Arkadaşlar", competition: "Lig ve geçmiş", cosmetics: "Stil odası" },
    cosmetics: { kicker: "SOYUNMA ODASI", title: "Kendi\nsahan.", pitch: "SAHA TEMASI", badge: "ROZET", equipped: "Kullanılıyor", equip: "Kullan", equipFailed: "Kozmetik kuşanılamadı. Bağlantını kontrol edip tekrar dene.", note: "Kozmetikler oynanışı veya süreleri değiştirmez.", starter: "Başlangıç koleksiyonu" },
    competition: { kicker: "SEZON 01", title: "Sahanın\nformu.", table: "LİG TABLOSU", history: "MAÇ GEÇMİŞİ", noHistory: "Henüz tamamlanmış maçın yok.", played: "O", win: "G", loss: "M", quickOnly: "Kupalar yalnızca Hızlı Maçta değişir.", winLabel: "GALİBİYET", lossLabel: "MAĞLUBİYET" },
    friends: { kicker: "TAKIM ARKADAŞLARI", title: "Arkadaşlarınla\noyna.", yourCode: "SENİN OYUNCU KODUN", retry: "Tekrar dene", addPlaceholder: "Oyuncu kodu · örn. #AB12CD", add: "Arkadaş ekle", empty: "Henüz arkadaşın yok. Oyuncu koduyla davet gönder.", pending: "BEKLEYEN DAVETLER", outgoing: "Gönderildi", accept: "Kabul et", decline: "Reddet", invite: "Maç daveti gönder", inviteTitle: "Arkadaşına davet gönder", inviteCopy: (name: string) => `${name} için bir oda aç ve davet bağlantısını paylaş.`, sent: "Arkadaşlık isteği gönderildi.", accepted: "Arkadaş eklendi.", errors: { PLAYER_NOT_FOUND: "Bu oyuncu koduna ait hesap bulunamadı.", INVALID_PLAYER_CODE: "Oyuncu kodu 6 harf veya rakamdan oluşmalı.", CANNOT_ADD_SELF: "Kendini arkadaş olarak ekleyemezsin.", FRIENDSHIP_UNAVAILABLE: "Bu oyuncuya şu anda istek gönderemezsin.", fallback: "Arkadaşlık işlemi tamamlanamadı." } },
    match: { exitTitle: "Maçtan çıkılsın mı?", exitCopy: "Çıkarsan bu maç rakibin lehine tamamlanır.", stay: "Maçta kal", exit: "Maçtan çık", live: "CANLI", connecting: "BAĞLANIYOR", you: "SEN", bot: "TEST BOT", opponent: "RAKİP", seconds: " sn", testMatch: "TEST MAÇI", testMatchCopy: "Bot yanlış cevap verir; doğrulama ve puan akışını sen kontrol edersin.", phases: { WAITING: "RAKİP BEKLENİYOR", READY: "HAZIRLIK", SELECTING: "TAKIM SEÇİMİ", COUNTDOWN: "BAŞLIYOR", ANSWERING: "CEVAP ZAMANI", REVEAL: "ROUND SONUCU", FINISHED: "MAÇ BİTTİ", PAUSED: "MAÇ DURAKLATILDI" }, errors: { ROOM_NOT_READY: "Maç odası hazırlanıyor. Birkaç saniye sonra tekrar dene.", NO_SELECTION: "Önce bir kulüp seç.", SELECTION_LOCKED: "Bu round için seçimin zaten kilitlendi.", ANSWER_DEADLINE_PASSED: "Cevap süresi doldu.", ALREADY_SUBMITTED: "Bu round için cevabın zaten gönderildi.", INVALID_PHASE: "Bu işlem mevcut maç aşamasında kullanılamıyor.", fallback: "İşlem tamamlanamadı. Tekrar dene.", invalidPair: "Bu eşleşmede ortak futbolcu bulunamadı. Yeniden seç." }, fieldPreparing: "Saha hazırlanıyor", botConnecting: "Test botu maça bağlanıyor…", playerNeeded: "Aynı oda koduyla ikinci oyuncunun katılması gerekiyor.", botReady: "Bot hazır. Sen?", opponentFound: "Rakibin bulundu.", readyCopy: "Maç başladığında takımını seçmek için 15 saniyen olacak.", readyAction: "Hazırım, başlat", pool: (count: number) => `KULÜP HAVUZU · ${count} UYGUN`, buildLink: "Bağlantıyı kur.", selectionBot: "Bir kulüp seç; bot ortak futbolcusu bulunan ikinci kulübü tamamlasın.", selectionPlayer: "Kulübünü seç; rakibin seçimi ikiniz de onayladığında açıklanır.", selectionLocked: "Seçim kilitlendi", confirmSelection: "Seçimi onayla", commonPlayer: "ORTAK FUTBOLCU", whoLinks: "Kimi bağlar?", answerA11y: "Futbolcu cevabı", answerPlaceholder: "Futbolcu adını yaz", answerSent: "Cevap gönderildi", sendAnswer: "Cevabı gönder", paused: "Maç durakladı", pausedCopy: "Rakibin yeniden bağlanması bekleniyor.", roundDone: "Round tamamlandı", matchDone: "Maç tamamlandı", newBotMatch: "Yeni test maçı", returnCenter: "Maç merkezine dön", referee: "HAKEM KARARI", roundYours: "Bu round senin.", roundOpponent: "Bu round rakibin.", noPoint: "Bu round puansız.", noAnswer: "Cevap yok", correct: "DOĞRU", wrong: "YANLIŞ", used: "KULLANILDI", scoreA11y: (score: number) => `${score} puan, kazanmak için 3 puan gerekli`, usedA11y: ", kullanıldı" },
    report: { action: "Sonucu bildir", title: "Neyi bildirmek istiyorsun?", wrongResult: "Sonuç hatalı", offensiveContent: "Uygunsuz içerik", otherIssue: "Diğer", cancel: "Vazgeç", sent: "Bildirim alındı", failed: "Bildirim gönderilemedi. Tekrar dene." },
    rematch: { action: "Rövanş iste", pending: "Rakibin yanıtı bekleniyor…", offerTitle: "Rövanş teklifi", offerCopy: "Rakibin yeni bir maç istiyor.", accept: "Kabul et", decline: "Reddet", declined: "Rakibin rövanş teklifini reddetti." },
    selection: { sameClub: "İkiniz de aynı takımı seçtiniz. Farklı iki takım seçin.", usedPair: "Bu takım eşleşmesi daha önce kullanıldı. Yeni iki takım seçin.", noCommonPlayer: "Seçilen takımlarda ortak futbolcu yok. Tekrar seçim yapın.", fallback: "Bu seçimle maç kurulamadı. Takımları tekrar seçin." },
    quick: { action: "Hızlı Maç", copy: "Rastgele bir rakiple hemen eşleş.", waiting: "Rakip aranıyor…", cancel: "Aramayı iptal et" },
    quickMessages: { GOOD_LUCK: "Bol şans! ⚽", NICE_ONE: "İyi oyundu! 🙌", SO_CLOSE: "Az farkla!", READY: "Hazırım.", REMATCH: "Rövanş? ↻" },
  },
  en: {
    common: { signIn: "Sign in", signUp: "Create account", player: "player", trophies: "trophies", chatStyle: "CHAT BUBBLE" },
    nav: { play: "Play", friends: "Friends", league: "League", style: "Style", account: "Account menu" },
    social: { online: "Online", inMatch: "In match", offline: "Offline", recent: "RECENT OPPONENTS", remove: "Remove friend", block: "Block", manage: "Manage friend", inviteSent: "Match invite sent" },
    effects: { lastSecond: "LAST-SECOND ANSWER", cooldown: "Wait a moment before sending another message" },
    auth: { checking: "Checking your session", kicker: "FOOTBALL LINK · MATCH LOGIN", title: "Two clubs.", titleAccent: "One link.", lead: "Put your football memory to the test against real opponents.", welcome: (name: string) => `Welcome, ${name}.`, activeMatch: "MATCH IN PROGRESS", botMatch: "Against the test bot", friendRoom: "Friend room", matchCenter: "Go to match center", displayName: "Display name", email: "Email", password: "Password · at least 6 characters", or: "OR", confirmationSent: "We sent a confirmation link to your email. You can sign in after confirming it.", errors: { invalidLogin: "Email or password did not match.", registered: "This email is already registered. Try signing in.", password: "Password must be at least 6 characters.", fallback: "The operation could not be completed. Check your connection and try again.", invalidResponse: "The sign-in response could not be verified." } },
    lobby: { signOut: "Sign out", noSession: "No session", kicker: "MATCH CENTER", title: "How do you want\nto play?", botA11y: "Start a test match against the bot", recommended: "RECOMMENDED FOR TESTING", botTitle: "Play against bot", botCopy: "Try the complete match flow on one device without waiting for an opponent.", botAction: "Start test match", friendRoom: "FRIEND ROOM", roomTitle: "Join the same room", roomCopy: "Create a room and send an invite, or enter your friend's code.", roomCode: "Match room code", createRoom: "Create new room", shareInvite: "Share invite", inviteTitle: "Football Link match invite", inviteMessage: (url: string) => `Play Football Link with me: ${url}`, roomCreated: "Room ready. Share the invite or join the match.", join: "Join room", friends: "Friends", competition: "League & history", cosmetics: "Style room" },
    cosmetics: { kicker: "LOCKER ROOM", title: "Your\npitch.", pitch: "PITCH THEME", badge: "BADGE", equipped: "Equipped", equip: "Equip", equipFailed: "Could not equip this cosmetic. Check your connection and try again.", note: "Cosmetics never change gameplay or timers.", starter: "Starter collection" },
    competition: { kicker: "SEASON 01", title: "Form on\nthe pitch.", table: "LEAGUE TABLE", history: "MATCH HISTORY", noHistory: "You have no completed matches yet.", played: "P", win: "W", loss: "L", quickOnly: "Trophies only change in Quick Match.", winLabel: "WIN", lossLabel: "LOSS" },
    friends: { kicker: "TEAMMATES", title: "Play with\nyour friends.", yourCode: "YOUR PLAYER CODE", retry: "Try again", addPlaceholder: "Player code · e.g. #AB12CD", add: "Add friend", empty: "No friends yet. Send an invite with a player code.", pending: "PENDING REQUESTS", outgoing: "Request sent", accept: "Accept", decline: "Decline", invite: "Send match invite", inviteTitle: "Invite your friend", inviteCopy: (name: string) => `Open a room for ${name} and share the invite link.`, sent: "Friend request sent.", accepted: "Friend added.", errors: { PLAYER_NOT_FOUND: "No account matches that player code.", INVALID_PLAYER_CODE: "Player codes contain 6 letters or numbers.", CANNOT_ADD_SELF: "You cannot add yourself as a friend.", FRIENDSHIP_UNAVAILABLE: "You cannot send a request to this player right now.", fallback: "The friend action could not be completed." } },
    match: { exitTitle: "Leave the match?", exitCopy: "Leaving will award the match to your opponent.", stay: "Stay in match", exit: "Leave match", live: "LIVE", connecting: "CONNECTING", you: "YOU", bot: "TEST BOT", opponent: "OPPONENT", seconds: " sec", testMatch: "TEST MATCH", testMatchCopy: "The bot answers incorrectly so you can test validation and scoring.", phases: { WAITING: "WAITING FOR OPPONENT", READY: "GET READY", SELECTING: "CLUB SELECTION", COUNTDOWN: "STARTING", ANSWERING: "ANSWER TIME", REVEAL: "ROUND RESULT", FINISHED: "MATCH OVER", PAUSED: "MATCH PAUSED" }, errors: { ROOM_NOT_READY: "The match room is getting ready. Try again in a few seconds.", NO_SELECTION: "Select a club first.", SELECTION_LOCKED: "Your selection is already locked for this round.", ANSWER_DEADLINE_PASSED: "Answer time has expired.", ALREADY_SUBMITTED: "Your answer for this round was already submitted.", INVALID_PHASE: "This action is unavailable in the current match phase.", fallback: "The operation could not be completed. Try again.", invalidPair: "These clubs have no shared player. Select again." }, fieldPreparing: "Preparing the pitch", botConnecting: "The test bot is joining…", playerNeeded: "A second player needs to join with the same room code.", botReady: "The bot is ready. Are you?", opponentFound: "Opponent found.", readyCopy: "You will have 15 seconds to select your club after the match starts.", readyAction: "I'm ready, start", pool: (count: number) => `CLUB POOL · ${count} AVAILABLE`, buildLink: "Build the link.", selectionBot: "Pick a club and the bot will complete the pair with a linked club.", selectionPlayer: "Pick a club; both choices are revealed after confirmation.", selectionLocked: "Selection locked", confirmSelection: "Confirm selection", commonPlayer: "COMMON PLAYER", whoLinks: "Who links them?", answerA11y: "Player answer", answerPlaceholder: "Enter the player's name", answerSent: "Answer submitted", sendAnswer: "Submit answer", paused: "Match paused", pausedCopy: "Waiting for your opponent to reconnect.", roundDone: "Round complete", matchDone: "Match complete", newBotMatch: "New test match", returnCenter: "Return to match center", referee: "REFEREE DECISION", roundYours: "You won this round.", roundOpponent: "Your opponent won this round.", noPoint: "No points this round.", noAnswer: "No answer", correct: "CORRECT", wrong: "WRONG", used: "USED", scoreA11y: (score: number) => `${score} points; 3 points needed to win`, usedA11y: ", used" },
    report: { action: "Report result", title: "What would you like to report?", wrongResult: "Incorrect result", offensiveContent: "Offensive content", otherIssue: "Other", cancel: "Cancel", sent: "Report received", failed: "The report could not be sent. Try again." },
    rematch: { action: "Request rematch", pending: "Waiting for your opponent…", offerTitle: "Rematch offer", offerCopy: "Your opponent wants another match.", accept: "Accept", decline: "Decline", declined: "Your opponent declined the rematch offer." },
    selection: { sameClub: "You both selected the same club. Choose two different clubs.", usedPair: "This club pair was already used. Choose two new clubs.", noCommonPlayer: "The selected clubs have no shared player. Choose again.", fallback: "This selection could not start a match. Choose clubs again." },
    quick: { action: "Quick Match", copy: "Get matched with a random opponent now.", waiting: "Finding an opponent…", cancel: "Cancel search" },
    quickMessages: { GOOD_LUCK: "Good luck! ⚽", NICE_ONE: "Nice one! 🙌", SO_CLOSE: "So close!", READY: "I'm ready.", REMATCH: "Rematch? ↻" },
  },
} as const;

export type Locale = keyof typeof dictionaries;
export const locale: Locale = Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase().startsWith("tr") ? "tr" : "en";
export const tr = dictionaries[locale];
