update public.clubs c
set league = v.league, country = v.country
from (values
('arsenal','Premier League','England'),
('chelsea','Premier League','England'),
('liverpool','Premier League','England'),
('manchester-united','Premier League','England'),
('manchester-city','Premier League','England'),
('tottenham','Premier League','England'),
('newcastle','Premier League','England'),
('aston-villa','Premier League','England'),
('everton','Premier League','England'),
('west-ham','Premier League','England'),
('leeds','Premier League','England'),
('nottingham-forest','Premier League','England'),
('leicester','Premier League','England'),
('southampton','Premier League','England'),
('real-madrid','La Liga','Spain'),
('barcelona','La Liga','Spain'),
('atletico-madrid','La Liga','Spain'),
('sevilla','La Liga','Spain'),
('valencia','La Liga','Spain'),
('villarreal','La Liga','Spain'),
('athletic-bilbao','La Liga','Spain'),
('real-sociedad','La Liga','Spain'),
('real-betis','La Liga','Spain'),
('deportivo-la-coruna','La Liga','Spain'),
('celta-vigo','La Liga','Spain'),
('malaga','La Liga','Spain'),
('juventus','Serie A','Italy'),
('ac-milan','Serie A','Italy'),
('inter-milan','Serie A','Italy'),
('roma','Serie A','Italy'),
('napoli','Serie A','Italy'),
('lazio','Serie A','Italy'),
('fiorentina','Serie A','Italy'),
('atalanta','Serie A','Italy'),
('parma','Serie A','Italy'),
('sampdoria','Serie A','Italy'),
('torino','Serie A','Italy'),
('bologna','Serie A','Italy'),
('bayern-munich','Bundesliga','Germany'),
('borussia-dortmund','Bundesliga','Germany'),
('bayer-leverkusen','Bundesliga','Germany'),
('schalke','Bundesliga','Germany'),
('rb-leipzig','Bundesliga','Germany'),
('eintracht-frankfurt','Bundesliga','Germany'),
('wolfsburg','Bundesliga','Germany'),
('stuttgart','Bundesliga','Germany'),
('werder-bremen','Bundesliga','Germany'),
('hamburg','Bundesliga','Germany'),
('borussia-monchengladbach','Bundesliga','Germany'),
('hoffenheim','Bundesliga','Germany'),
('psg','Ligue 1','France'),
('marseille','Ligue 1','France'),
('lyon','Ligue 1','France'),
('monaco','Ligue 1','France'),
('lille','Ligue 1','France'),
('nice','Ligue 1','France'),
('rennes','Ligue 1','France'),
('bordeaux','Ligue 1','France'),
('saint-etienne','Ligue 1','France'),
('lens','Ligue 1','France'),
('nantes','Ligue 1','France'),
('montpellier','Ligue 1','France'),
('galatasaray','Süper Lig','Türkiye'),
('fenerbahce','Süper Lig','Türkiye'),
('besiktas','Süper Lig','Türkiye'),
('trabzonspor','Süper Lig','Türkiye'),
('istanbul-basaksehir','Süper Lig','Türkiye'),
('bursaspor','Süper Lig','Türkiye'),
('genclerbirligi','Süper Lig','Türkiye'),
('sivasspor','Süper Lig','Türkiye'),
('goztepe','Süper Lig','Türkiye'),
('konyaspor','Süper Lig','Türkiye'),
('kayserispor','Süper Lig','Türkiye'),
('adana-demirspor','Süper Lig','Türkiye'),
('antalyaspor','Süper Lig','Türkiye'),
('kasimpasa','Süper Lig','Türkiye'),
('benfica','Primeira Liga','Portugal'),
('porto','Primeira Liga','Portugal'),
('sporting-cp','Primeira Liga','Portugal'),
('braga','Primeira Liga','Portugal'),
('vitoria-guimaraes','Primeira Liga','Portugal'),
('boavista','Primeira Liga','Portugal'),
('ajax','Eredivisie','Netherlands'),
('psv','Eredivisie','Netherlands'),
('feyenoord','Eredivisie','Netherlands'),
('az-alkmaar','Eredivisie','Netherlands'),
('twente','Eredivisie','Netherlands'),
('utrecht','Eredivisie','Netherlands'),
('anderlecht','Belgian Pro League','Belgium'),
('club-brugge','Belgian Pro League','Belgium'),
('genk','Belgian Pro League','Belgium'),
('standard-liege','Belgian Pro League','Belgium'),
('gent','Belgian Pro League','Belgium'),
('celtic','Scottish Premiership','Scotland'),
('rangers','Scottish Premiership','Scotland'),
('aberdeen','Scottish Premiership','Scotland'),
('hearts','Scottish Premiership','Scotland'),
('olympiacos','Super League Greece','Greece'),
('panathinaikos','Super League Greece','Greece'),
('aek-athens','Super League Greece','Greece'),
('paok','Super League Greece','Greece'),
('red-bull-salzburg','Austrian Bundesliga','Austria'),
('rapid-wien','Austrian Bundesliga','Austria'),
('austria-wien','Austrian Bundesliga','Austria'),
('shakhtar-donetsk','Ukrainian Premier League','Ukraine'),
('dynamo-kyiv','Ukrainian Premier League','Ukraine'),
('dnipro','Ukrainian Premier League','Ukraine'),
('dinamo-zagreb','Croatian Football League','Croatia'),
('hajduk-split','Croatian Football League','Croatia'),
('red-star-belgrade','Serbian SuperLiga','Serbia'),
('partizan','Serbian SuperLiga','Serbia'),
('sparta-prague','Czech First League','Czechia'),
('slavia-prague','Czech First League','Czechia'),
('basel','Swiss Super League','Switzerland'),
('young-boys','Swiss Super League','Switzerland'),
('copenhagen','Danish Superliga','Denmark'),
('brondby','Danish Superliga','Denmark'),
('al-hilal','Saudi Pro League','Saudi Arabia'),
('al-nassr','Saudi Pro League','Saudi Arabia'),
('al-ittihad','Saudi Pro League','Saudi Arabia'),
('al-ahli-saudi','Saudi Pro League','Saudi Arabia'),
('inter-miami','Major League Soccer','United States'),
('la-galaxy','Major League Soccer','United States'),
('new-york-city','Major League Soccer','United States'),
('boca-juniors','Argentine Primera División','Argentina'),
('river-plate','Argentine Primera División','Argentina'),
('racing-club','Argentine Primera División','Argentina'),
('flamengo','Campeonato Brasileiro Série A','Brazil'),
('corinthians','Campeonato Brasileiro Série A','Brazil'),
('santos','Campeonato Brasileiro Série A','Brazil'),
('palmeiras','Campeonato Brasileiro Série A','Brazil')
) as v(external_id, league, country)
where c.external_id = v.external_id;
