create index if not exists club_pair_players_low_idx on public.club_pair_players(club_low_id);
create index if not exists club_pair_players_high_idx on public.club_pair_players(club_high_id);
create index if not exists club_pair_players_player_idx on public.club_pair_players(player_id);
create index if not exists club_pair_stats_low_idx on public.club_pair_stats(club_low_id);
create index if not exists club_pair_stats_high_idx on public.club_pair_stats(club_high_id);
create index if not exists football_data_versions_published_by_idx on public.football_data_versions(published_by);
create index if not exists friendships_addressee_idx on public.friendships(addressee_id);
create index if not exists matches_player_one_idx on public.matches(player_one_id);
create index if not exists matches_player_two_idx on public.matches(player_two_id);
create index if not exists matches_winner_idx on public.matches(winner_id);
create index if not exists matches_data_version_idx on public.matches(football_data_version_id);
create index if not exists contracts_club_idx on public.player_club_contracts(club_id);
create index if not exists result_reports_round_idx on public.result_reports(round_id);
create index if not exists result_reports_reporter_idx on public.result_reports(reporter_id);
create index if not exists rounds_club_low_idx on public.rounds(club_low_id);
create index if not exists rounds_club_high_idx on public.rounds(club_high_id);
create index if not exists rounds_winner_idx on public.rounds(winner_id);
create index if not exists submissions_player_idx on public.submissions(player_id);
create index if not exists user_blocks_blocked_idx on public.user_blocks(blocked_id);

drop policy if exists profile_self_update on public.profiles;
create policy profile_self_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
drop policy if exists own_matches_read on public.matches;
create policy own_matches_read on public.matches for select to authenticated using((select auth.uid()) in(player_one_id,player_two_id));
drop policy if exists own_rounds_read on public.rounds;
create policy own_rounds_read on public.rounds for select to authenticated using(exists(select 1 from public.matches m where m.id=match_id and (select auth.uid()) in(m.player_one_id,m.player_two_id)));
drop policy if exists own_reports on public.result_reports;
create policy own_reports on public.result_reports for all to authenticated using(reporter_id=(select auth.uid())) with check(reporter_id=(select auth.uid()));
drop policy if exists own_friendships on public.friendships;
create policy own_friendships on public.friendships for all to authenticated using((select auth.uid()) in(requester_id,addressee_id)) with check(requester_id=(select auth.uid()));
drop policy if exists own_blocks on public.user_blocks;
create policy own_blocks on public.user_blocks for all to authenticated using(blocker_id=(select auth.uid())) with check(blocker_id=(select auth.uid()));
