create extension if not exists pgcrypto;
create type public.data_version_status as enum ('DRAFT','STAGING','ACTIVE','ROLLED_BACK','ARCHIVED');
create type public.match_status as enum ('WAITING','ACTIVE','FINISHED','CANCELLED');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Player', player_code text not null unique, avatar_url text, trophies integer not null default 0 check(trophies>=0), created_at timestamptz not null default now());
create table public.football_data_versions (id uuid primary key default gen_random_uuid(), version_number text not null unique, status public.data_version_status not null default 'DRAFT', source_export_hash text not null unique, published_at timestamptz, published_by uuid references public.profiles(id), notes text, created_at timestamptz not null default now());
create unique index one_active_football_data_version on public.football_data_versions((status)) where status='ACTIVE';
create table public.clubs (id uuid primary key default gen_random_uuid(), external_id text not null unique, name text not null, country text, league text, active boolean not null default true, created_at timestamptz not null default now());
create table public.players (id uuid primary key default gen_random_uuid(), external_id text not null unique, game_name text not null, normalized_game_name text not null, created_at timestamptz not null default now());
create table public.player_aliases (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players on delete cascade, alias text not null, normalized_alias text not null, is_accepted_answer boolean not null default false, source text not null default 'IMPORT', unique(player_id,normalized_alias));
create index player_alias_lookup on public.player_aliases(normalized_alias) where is_accepted_answer;
create table public.player_club_contracts (id uuid primary key default gen_random_uuid(), player_id uuid not null references public.players on delete cascade, club_id uuid not null references public.clubs on delete cascade, starts_on date, ends_on date, contract_type text not null default 'UNKNOWN', squad_level text not null default 'FIRST_TEAM', source text not null default 'IMPORT', unique(player_id,club_id,starts_on,ends_on,source));
create table public.club_pair_players (football_data_version_id uuid not null references public.football_data_versions on delete cascade, club_low_id uuid not null references public.clubs on delete cascade, club_high_id uuid not null references public.clubs on delete cascade, player_id uuid not null references public.players on delete cascade, is_active boolean not null default true, primary key(football_data_version_id,club_low_id,club_high_id,player_id), check(club_low_id::text<club_high_id::text));
create index club_pair_lookup on public.club_pair_players(football_data_version_id,club_low_id,club_high_id) where is_active;
create table public.club_pair_stats (football_data_version_id uuid not null references public.football_data_versions on delete cascade, club_low_id uuid not null references public.clubs on delete cascade, club_high_id uuid not null references public.clubs on delete cascade, valid_player_count integer not null check(valid_player_count>=0), primary key(football_data_version_id,club_low_id,club_high_id), check(club_low_id::text<club_high_id::text));
create table public.football_data_import_runs (id uuid primary key default gen_random_uuid(), source text not null, started_at timestamptz not null default now(), finished_at timestamptz, status text not null, clubs_inserted integer not null default 0, players_inserted integer not null default 0, memberships_inserted integer not null default 0, aliases_inserted integer not null default 0, pairs_generated integer not null default 0, errors jsonb, export_hash text not null unique);
create table public.matches (id uuid primary key default gen_random_uuid(), mode text not null check(mode in('QUICK','FRIEND','DEVELOPMENT')), status public.match_status not null default 'WAITING', player_one_id uuid not null references public.profiles, player_two_id uuid references public.profiles, winner_id uuid references public.profiles, football_data_version_id uuid not null references public.football_data_versions, score_one smallint not null default 0, score_two smallint not null default 0, created_at timestamptz not null default now(), finished_at timestamptz);
create table public.rounds (id uuid primary key default gen_random_uuid(), match_id uuid not null references public.matches on delete cascade, round_number smallint not null, sudden_death boolean not null default false, club_low_id uuid not null references public.clubs, club_high_id uuid not null references public.clubs, winner_id uuid references public.profiles, started_at timestamptz not null default now(), finished_at timestamptz, unique(match_id,round_number,sudden_death), check(club_low_id::text<club_high_id::text));
create table public.submissions (id uuid primary key default gen_random_uuid(), round_id uuid not null references public.rounds on delete cascade, player_id uuid not null references public.profiles, raw_answer text not null, normalized_answer text not null, is_correct boolean not null, received_at timestamptz not null default now(), submission_sequence bigint not null, client_command_id text not null, unique(round_id,player_id), unique(round_id,submission_sequence), unique(round_id,client_command_id));
create table public.friendships (requester_id uuid references public.profiles on delete cascade, addressee_id uuid references public.profiles on delete cascade, status text not null, created_at timestamptz not null default now(), primary key(requester_id,addressee_id), check(requester_id<>addressee_id));
create table public.user_blocks (blocker_id uuid references public.profiles on delete cascade, blocked_id uuid references public.profiles on delete cascade, created_at timestamptz not null default now(), primary key(blocker_id,blocked_id), check(blocker_id<>blocked_id));
create table public.result_reports (id uuid primary key default gen_random_uuid(), match_id uuid not null references public.matches, round_id uuid references public.rounds, reporter_id uuid not null references public.profiles, reason_code text not null, detail text, status text not null default 'OPEN', created_at timestamptz not null default now(), unique(match_id,round_id,reporter_id));

alter table public.profiles enable row level security; alter table public.clubs enable row level security; alter table public.players enable row level security; alter table public.player_aliases enable row level security; alter table public.player_club_contracts enable row level security; alter table public.club_pair_players enable row level security; alter table public.club_pair_stats enable row level security; alter table public.football_data_versions enable row level security; alter table public.football_data_import_runs enable row level security; alter table public.matches enable row level security; alter table public.rounds enable row level security; alter table public.submissions enable row level security; alter table public.friendships enable row level security; alter table public.user_blocks enable row level security; alter table public.result_reports enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(true); create policy profile_self_update on public.profiles for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
create policy clubs_read on public.clubs for select to authenticated using(active); create policy versions_read on public.football_data_versions for select to authenticated using(status='ACTIVE');
create policy own_matches_read on public.matches for select to authenticated using(auth.uid() in(player_one_id,player_two_id)); create policy own_rounds_read on public.rounds for select to authenticated using(exists(select 1 from public.matches m where m.id=match_id and auth.uid() in(m.player_one_id,m.player_two_id)));
create policy own_reports on public.result_reports for all to authenticated using(reporter_id=auth.uid()) with check(reporter_id=auth.uid());
create policy own_friendships on public.friendships for all to authenticated using(auth.uid() in(requester_id,addressee_id)) with check(requester_id=auth.uid()); create policy own_blocks on public.user_blocks for all to authenticated using(blocker_id=auth.uid()) with check(blocker_id=auth.uid());
-- No client policies exist for answers, aliases, contracts, pair data, submissions or import runs.
