-- Small, earnable coin economy for daily quests and cosmetic purchases.

alter table public.profiles
  add column if not exists coins integer not null default 0 check (coins >= 0);

-- Profiles previously had a broad self-update policy. Keep editable profile fields
-- client-writable without allowing clients to mint coins or trophies directly.
revoke update on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, avatar_url) on public.profiles to authenticated;

alter table public.quest_definitions
  add column if not exists reward_coins smallint not null default 0 check (reward_coins between 0 and 100);

update public.quest_definitions set reward_coins = case id
  when 'daily_finish_match' then 3
  when 'daily_correct_answer' then 4
  when 'daily_social_touch' then 3
  else reward_coins
end
where kind = 'DAILY';

alter table public.cosmetic_items
  add column if not exists price_coins integer not null default 0 check (price_coins >= 0);

update public.cosmetic_items set price_coins = case id
  when 'emote-goat' then 18
  when 'emote-crown' then 24
  when 'emote-bolt' then 15
  when 'emote-trophy' then 22
  when 'emote-skull' then 16
  when 'emote-party' then 14
  when 'emote-cold' then 20
  when 'emote-heart' then 12
  else 0
end;

create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null check (amount <> 0),
  reason text not null check (reason in ('DAILY_QUEST', 'COSMETIC_PURCHASE')),
  reference_id text not null,
  balance_after integer not null check (balance_after >= 0),
  created_at timestamptz not null default now(),
  unique (player_id, reason, reference_id)
);
create index if not exists coin_transactions_player_created_idx
  on public.coin_transactions(player_id, created_at desc);
alter table public.coin_transactions enable row level security;
revoke all on public.coin_transactions from public, anon, authenticated;

drop function if exists public.quests_mine();
create function public.quests_mine()
returns table(
  quest_id text,
  metric text,
  progress integer,
  target_count integer,
  completed boolean,
  claimed boolean,
  quest_day date,
  reward_coins smallint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  day date := (timezone('utc', now()))::date;
begin
  if me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  perform public._quests_ensure_day(me, day);
  return query
  select u.quest_id, d.metric, u.progress, u.target_count,
         u.completed_at is not null, u.claimed_at is not null, u.quest_day, d.reward_coins
  from public.user_daily_quests u
  join public.quest_definitions d on d.id = u.quest_id
  where u.player_id = me and u.quest_day = day and d.active
  order by d.sort_order, u.quest_id;
end;
$$;

drop function if exists public.quests_claim(text);
create function public.quests_claim(p_quest_id text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  day date := (timezone('utc', now()))::date;
  reward smallint;
  new_balance integer;
begin
  if me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  perform public._quests_ensure_day(me, day);

  -- Lock the wallet before resolving the claim so concurrent requests serialize.
  select p.coins into new_balance from public.profiles p where p.id = me for update;
  if not found then raise exception 'PROFILE_NOT_FOUND'; end if;

  update public.user_daily_quests u
  set claimed_at = now()
  from public.quest_definitions d
  where u.player_id = me
    and u.quest_day = day
    and u.quest_id = p_quest_id
    and u.quest_id = d.id
    and u.completed_at is not null
    and u.claimed_at is null
  returning d.reward_coins into reward;

  if reward is null then
    if exists (
      select 1 from public.user_daily_quests
      where player_id = me and quest_day = day and quest_id = p_quest_id and claimed_at is not null
    ) then
      return new_balance;
    end if;
    raise exception 'QUEST_NOT_CLAIMABLE';
  end if;

  update public.profiles set coins = coins + reward where id = me returning coins into new_balance;
  insert into public.coin_transactions(player_id, amount, reason, reference_id, balance_after)
  values (me, reward, 'DAILY_QUEST', day::text || ':' || p_quest_id, new_balance);
  return new_balance;
end;
$$;

drop function if exists public.cosmetics_mine();
create function public.cosmetics_mine()
returns table(
  item_id text,
  name text,
  kind text,
  accent text,
  equipped boolean,
  is_premium boolean,
  glyph text,
  owned boolean,
  price_coins integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
begin
  if me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;

  insert into public.user_cosmetics(player_id, item_id)
  select me, c.id from public.cosmetic_items c
  where c.available and not c.is_premium
  on conflict do nothing;

  insert into public.user_cosmetic_loadouts(player_id, pitch_theme_id, badge_id, chat_style_id)
  values (me, 'pitch-classic', 'badge-link', 'chat-classic')
  on conflict (player_id) do nothing;

  update public.user_cosmetic_loadouts
  set chat_style_id = coalesce(chat_style_id, 'chat-classic')
  where player_id = me;

  return query
  select c.id, c.name, c.kind, c.accent,
         (l.pitch_theme_id = c.id or l.badge_id = c.id or l.chat_style_id = c.id),
         c.is_premium, c.glyph,
         exists (select 1 from public.user_cosmetics u where u.player_id = me and u.item_id = c.id),
         c.price_coins
  from public.cosmetic_items c
  join public.user_cosmetic_loadouts l on l.player_id = me
  where c.available
  order by case c.kind when 'EMOTE' then 0 when 'CHAT_STYLE' then 1 when 'PITCH_THEME' then 2 else 3 end,
           c.is_premium, c.price_coins, c.id;
end;
$$;

drop function if exists public.cosmetics_purchase(text);
create function public.cosmetics_purchase(p_item_id text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  item public.cosmetic_items%rowtype;
  new_balance integer;
begin
  if me is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
  select * into item from public.cosmetic_items where id = p_item_id and available;
  if not found then raise exception 'COSMETIC_NOT_FOUND'; end if;

  select p.coins into new_balance from public.profiles p where p.id = me for update;
  if not found then raise exception 'PROFILE_NOT_FOUND'; end if;

  if exists (select 1 from public.user_cosmetics where player_id = me and item_id = item.id) then
    return new_balance;
  end if;
  if item.price_coins <= 0 then raise exception 'COSMETIC_NOT_FOR_SALE'; end if;

  update public.profiles
  set coins = coins - item.price_coins
  where id = me and coins >= item.price_coins
  returning coins into new_balance;
  if not found then raise exception 'INSUFFICIENT_COINS'; end if;

  insert into public.user_cosmetics(player_id, item_id) values (me, item.id);
  insert into public.coin_transactions(player_id, amount, reason, reference_id, balance_after)
  values (me, -item.price_coins, 'COSMETIC_PURCHASE', item.id, new_balance);
  return new_balance;
end;
$$;

revoke all on function public.quests_mine() from public, anon;
revoke all on function public.quests_claim(text) from public, anon;
revoke all on function public.cosmetics_mine() from public, anon;
revoke all on function public.cosmetics_purchase(text) from public, anon;
grant execute on function public.quests_mine() to authenticated;
grant execute on function public.quests_claim(text) to authenticated;
grant execute on function public.cosmetics_mine() to authenticated;
grant execute on function public.cosmetics_purchase(text) to authenticated;
