-- backfill club league/country from builder config
update public.clubs set league='Premier League', country='England' where external_id='arsenal';
update public.clubs set league='Premier League', country='England' where external_id='chelsea';
update public.clubs set league='Premier League', country='England' where external_id='liverpool';
update public.clubs set league='Premier League', country='England' where external_id='manchester-united';
update public.clubs set league='Premier League', country='England' where external_id='manchester-city';
update public.clubs set league='Premier League', country='England' where external_id='tottenham';
update public.clubs set league='Premier League', country='England' where external_id='newcastle';
update public.clubs set league='Premier League', country='England' where external_id='aston-villa';
update public.clubs set league='Premier League', country='England' where external_id='everton';
update public.clubs set league='Premier League', country='England' where external_id='west-ham';
update public.clubs set league='Premier League', country='England' where external_id='leeds';
update public.clubs set league='Premier League', country='England' where external_id='nottingham-forest';
update public.clubs set league='Premier League', country='England' where external_id='leicester';
update public.clubs set league='Premier League', country='England' where external_id='southampton';
update public.clubs set league='La Liga', country='Spain' where external_id='real-madrid';
update public.clubs set league='La Liga', country='Spain' where external_id='barcelona';
update public.clubs set league='La Liga', country='Spain' where external_id='atletico-madrid';
update public.clubs set league='La Liga', country='Spain' where external_id='sevilla';
update public.clubs set league='La Liga', country='Spain' where external_id='valencia';
update public.clubs set league='La Liga', country='Spain' where external_id='villarreal';
update public.clubs set league='La Liga', country='Spain' where external_id='athletic-bilbao';
update public.clubs set league='La Liga', country='Spain' where external_id='real-sociedad';
update public.clubs set league='La Liga', country='Spain' where external_id='real-betis';
update public.clubs set league='La Liga', country='Spain' where external_id='deportivo-la-coruna';
update public.clubs set league='La Liga', country='Spain' where external_id='celta-vigo';
update public.clubs set league='La Liga', country='Spain' where external_id='malaga';
update public.clubs set league='Serie A', country='Italy' where external_id='juventus';
update public.clubs set league='Serie A', country='Italy' where external_id='ac-milan';
update public.clubs set league='Serie A', country='Italy' where external_id='inter-milan';
update public.clubs set league='Serie A', country='Italy' where external_id='roma';
update public.clubs set league='Serie A', country='Italy' where external_id='napoli';
update public.clubs set league='Serie A', country='Italy' where external_id='lazio';
update public.clubs set league='Serie A', country='Italy' where external_id='fiorentina';
update public.clubs set league='Serie A', country='Italy' where external_id='atalanta';
update public.clubs set league='Serie A', country='Italy' where external_id='parma';
update public.clubs set league='Serie A', country='Italy' where external_id='sampdoria';
update public.clubs set league='Serie A', country='Italy' where external_id='torino';
update public.clubs set league='Serie A', country='Italy' where external_id='bologna';
update public.clubs set league='Bundesliga', country='Germany' where external_id='bayern-munich';
update public.clubs set league='Bundesliga', country='Germany' where external_id='borussia-dortmund';
update public.clubs set league='Bundesliga', country='Germany' where external_id='bayer-leverkusen';
update public.clubs set league='Bundesliga', country='Germany' where external_id='schalke';
update public.clubs set league='Bundesliga', country='Germany' where external_id='rb-leipzig';
update public.clubs set league='Bundesliga', country='Germany' where external_id='eintracht-frankfurt';
update public.clubs set league='Bundesliga', country='Germany' where external_id='wolfsburg';
update public.clubs set league='Bundesliga', country='Germany' where external_id='stuttgart';
update public.clubs set league='Bundesliga', country='Germany' where external_id='werder-bremen';
update public.clubs set league='Bundesliga', country='Germany' where external_id='hamburg';
update public.clubs set league='Bundesliga', country='Germany' where external_id='borussia-monchengladbach';
update public.clubs set league='Bundesliga', country='Germany' where external_id='hoffenheim';
update public.clubs set league='Ligue 1', country='France' where external_id='psg';
update public.clubs set league='Ligue 1', country='France' where external_id='marseille';
update public.clubs set league='Ligue 1', country='France' where external_id='lyon';
update public.clubs set league='Ligue 1', country='France' where external_id='monaco';
update public.clubs set league='Ligue 1', country='France' where external_id='lille';
update public.clubs set league='Ligue 1', country='France' where external_id='nice';
update public.clubs set league='Ligue 1', country='France' where external_id='rennes';
update public.clubs set league='Ligue 1', country='France' where external_id='bordeaux';
update public.clubs set league='Ligue 1', country='France' where external_id='saint-etienne';
update public.clubs set league='Ligue 1', country='France' where external_id='lens';
update public.clubs set league='Ligue 1', country='France' where external_id='nantes';
update public.clubs set league='Ligue 1', country='France' where external_id='montpellier';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='galatasaray';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='fenerbahce';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='besiktas';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='trabzonspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='istanbul-basaksehir';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='bursaspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='genclerbirligi';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='sivasspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='goztepe';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='konyaspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='kayserispor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='adana-demirspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='antalyaspor';
update public.clubs set league='Süper Lig', country='Türkiye' where external_id='kasimpasa';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='benfica';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='porto';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='sporting-cp';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='braga';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='vitoria-guimaraes';
update public.clubs set league='Primeira Liga', country='Portugal' where external_id='boavista';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='ajax';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='psv';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='feyenoord';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='az-alkmaar';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='twente';
update public.clubs set league='Eredivisie', country='Netherlands' where external_id='utrecht';
update public.clubs set league='Belgian Pro League', country='Belgium' where external_id='anderlecht';
update public.clubs set league='Belgian Pro League', country='Belgium' where external_id='club-brugge';
update public.clubs set league='Belgian Pro League', country='Belgium' where external_id='genk';
update public.clubs set league='Belgian Pro League', country='Belgium' where external_id='standard-liege';
update public.clubs set league='Belgian Pro League', country='Belgium' where external_id='gent';
update public.clubs set league='Scottish Premiership', country='Scotland' where external_id='celtic';
update public.clubs set league='Scottish Premiership', country='Scotland' where external_id='rangers';
update public.clubs set league='Scottish Premiership', country='Scotland' where external_id='aberdeen';
update public.clubs set league='Scottish Premiership', country='Scotland' where external_id='hearts';
update public.clubs set league='Super League Greece', country='Greece' where external_id='olympiacos';
update public.clubs set league='Super League Greece', country='Greece' where external_id='panathinaikos';
update public.clubs set league='Super League Greece', country='Greece' where external_id='aek-athens';
update public.clubs set league='Super League Greece', country='Greece' where external_id='paok';
update public.clubs set league='Austrian Bundesliga', country='Austria' where external_id='red-bull-salzburg';
update public.clubs set league='Austrian Bundesliga', country='Austria' where external_id='rapid-wien';
update public.clubs set league='Austrian Bundesliga', country='Austria' where external_id='austria-wien';
update public.clubs set league='Ukrainian Premier League', country='Ukraine' where external_id='shakhtar-donetsk';
update public.clubs set league='Ukrainian Premier League', country='Ukraine' where external_id='dynamo-kyiv';
update public.clubs set league='Ukrainian Premier League', country='Ukraine' where external_id='dnipro';
update public.clubs set league='Croatian Football League', country='Croatia' where external_id='dinamo-zagreb';
update public.clubs set league='Croatian Football League', country='Croatia' where external_id='hajduk-split';
update public.clubs set league='Serbian SuperLiga', country='Serbia' where external_id='red-star-belgrade';
update public.clubs set league='Serbian SuperLiga', country='Serbia' where external_id='partizan';
update public.clubs set league='Czech First League', country='Czechia' where external_id='sparta-prague';
update public.clubs set league='Czech First League', country='Czechia' where external_id='slavia-prague';
update public.clubs set league='Swiss Super League', country='Switzerland' where external_id='basel';
update public.clubs set league='Swiss Super League', country='Switzerland' where external_id='young-boys';
update public.clubs set league='Danish Superliga', country='Denmark' where external_id='copenhagen';
update public.clubs set league='Danish Superliga', country='Denmark' where external_id='brondby';
update public.clubs set league='Saudi Pro League', country='Saudi Arabia' where external_id='al-hilal';
update public.clubs set league='Saudi Pro League', country='Saudi Arabia' where external_id='al-nassr';
update public.clubs set league='Saudi Pro League', country='Saudi Arabia' where external_id='al-ittihad';
update public.clubs set league='Saudi Pro League', country='Saudi Arabia' where external_id='al-ahli-saudi';
update public.clubs set league='Major League Soccer', country='United States' where external_id='inter-miami';
update public.clubs set league='Major League Soccer', country='United States' where external_id='la-galaxy';
update public.clubs set league='Major League Soccer', country='United States' where external_id='new-york-city';
update public.clubs set league='Argentine Primera División', country='Argentina' where external_id='boca-juniors';
update public.clubs set league='Argentine Primera División', country='Argentina' where external_id='river-plate';
update public.clubs set league='Argentine Primera División', country='Argentina' where external_id='racing-club';
update public.clubs set league='Campeonato Brasileiro Série A', country='Brazil' where external_id='flamengo';
update public.clubs set league='Campeonato Brasileiro Série A', country='Brazil' where external_id='corinthians';
update public.clubs set league='Campeonato Brasileiro Série A', country='Brazil' where external_id='santos';
update public.clubs set league='Campeonato Brasileiro Série A', country='Brazil' where external_id='palmeiras';
